# Generated by Django 5.0.6 on 2024-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_receipe_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
